name: Build

on:
  - push
  - workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build -x signArchives

      - name: Build gh-pages
        if: github.ref == 'refs/heads/master'
        run: |
          ./gradlew npmInstall
          npx ng build --base-href=./
          cp dist/springwolf-ui/asyncapi-ui.html dist/springwolf-ui/index.html
      - name: Deploy to gh pages 🚀
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/springwolf-ui/
