name: springwolf-ui

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

  deploy-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.18.x
      
      - name: Install
        run: npm install
      
      - name: Build
        run: ng build --base-href=https://springwolf.github.io/springwolf-ui/
        
      - name: Rename asyncapi-ui.html to index html
        run: mv dist/springwolf-ui/asyncapi-ui.html dist/springwolf-ui/index.html
      
      - name: Fix asyncapi image location
        run: find . -name '*.js' -exec sed -i -e 's~../../assets/asyncapi-logo.png~https://springwolf.github.io/springwolf-ui/assets/asyncapi-logo.png~g' {} \;

      - name: Deploy to gh-pages
        run: ng deploy --no-build
